### ISSUE TITLE
XML schema issue after submitting a transaction

### ISSUE THREAD

**Issue by interose** [nemiah/phpSepaXml#2]
As proposed I'm going to create the issue at the right place, because I openend it at the wrong place / repository.

Here is the initial issue:  #https://github.com/nemiah/phpFinTS/issues/399

@nemiah Should I create a PR?

**Comment by nemiah** [comment]
Hi and thank you for your offer. I took the occasion and merged some changes to "upstream" that I had done a while back.

Feel free to try if it works now and if it does not, I'd appreciate your PR.

**Comment by interose** [comment]
Hi, thanks for the response. I checked the changes but the bank institute still complains about the payment initiation. 
The DKB (and obviously the Sparkasse) recently doesn't allow the german pain format anymore.  (which is weird because they are german institutes, but that's another topic)

I have added a PR where I very simply added the possiblity to overwrite the pain. It is my very first PR, so please be kind if there is something wrong or missing ;)
Marcus

**Comment by Heart1010** [comment]
> allow the german pain format anymore

What do you mean here?
The pain formats are simply outdated (see lifecycle https://www.ebics.de/de/datenformate/format-lifecycle), you have to use the new pain format(s).

![image](https://user-images.githubusercontent.com/1481680/223156058-b145c686-ae42-49d2-a378-9d9e224ae9bf.png)

**Comment by nemiah** [comment]
> 



> Hi, thanks for the response. I checked the changes but the bank institute still complains about the payment initiation. The DKB (and obviously the Sparkasse) recently doesn't allow the german pain format anymore. (which is weird because they are german institutes, but that's another topic)
> 
> I have added a PR where I very simply added the possiblity to overwrite the pain. It is my very first PR, so please be kind if there is something wrong or missing ;) Marcus

Thank you, looks fine :relaxed:

**Comment by interose** [comment]
@Heart1010 didn't know that. Thanks for the clarification!
